#!/bin/bash

get_installed_xsessions() {
	names=()
	executables=()
	xsessions=($(ls /usr/share/xsessions/*.desktop))
	for xsession in ${xsessions[@]}; do
		names+=("$(awk -F '=' '/^Name=/ {print $2}' $xsession)")
		executables+=("$(awk -F '=' '/^Exec=/ {print $2}' $xsession)")
	done
	executables+=("")
}

choose_xsession() {
	PS3='Choose a WM/DE for your X session: '
	select opt in "${names[@]}"
	do
	    if [ ! -z ${executables[$REPLY - 1]} ]; then
		WINDOWMANAGER=${executables[$REPLY - 1]} startx
		break
	    fi
	done
}

get_installed_xsessions
choose_xsession
