#!/bin/bash

add="Add todo"
remove="Remove todo"

case "$(echo -e "$add\n$remove" | dmenu)" in
	"$add")
		cat ~/.todo-list | dmenu -l 10 -p "$add" >> ~/.todo-list
	;;
	"$remove")
		sed -i "/^$(cat ~/.todo-list | dmenu -l 10 -p "$remove")$/d" ~/.todo-list
	;;
esac
